### ISSUE TITLE
serverlessrepo giving old version

### ISSUE THREAD

**Issue by BarryGr** [DataDog/datadog-lambda-layer-python#38]
## Expected Behavior
latest stable should be use on install and ideally updates should update to latest or give options to update in stages.

## Actual Behavior
https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:464622532012:applications~Datadog-Log-Forwarder

#always v3 and python 2.7

**Comment by sfirrin** [comment]
Hey @BarryGr, sorry for the delay in getting back to you here. 

If I'm understanding your issue correctly it's in reference to the Datadog Forwarder rather than the Python layer (where this issue was opened), but we're the same team maintaining both so I can answer here.

We've recently deprecated the serverless repo method of installing a Datadog Forwarder in favor of a CloudFormation stack that is a lot easier to use. You can find more information and upgrade instructions in the [Datadog Forwarder readme](https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring).

I'm going to close out this issue, please feel free to open a new issue in the [datadog-serverless-functions](https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring) repository or open a ticket with Datadog support if you're still running into problems with the Forwarder.
