### ISSUE TITLE
Datadog Tracer not including env tag on spans

### ISSUE THREAD

**Issue by hydrosquall** [DataDog/datadog-lambda-layer-python#59]
## Expected Behavior

- env tag is set to the value of `DD_ENV` or the AWS "env" tag for ddtrace spans

## Actual Behavior

- env tag is always `none`

## Steps to Reproduce the Problem

  1. Followed the directions from the [README.md](https://github.com/DataDog/datadog-lambda-layer-python#datadog-tracer-beta) to set up datadog tracer
  2. Set the environment variable for `DD_ENV` to `staging`, per DDTrace [docs](http://pypi.datadoghq.com/trace/docs/configuration.html), and redeploy app
  3. Go to "live tail" search, observe that is `env:none` for all `ddtrace` spans, but set correctly to `staging` for all aws xray traces.

## Specifications

  - Datadog Lambda Layer version: `Datadog-Python37:15`
  - Python version: 3.7

**Comment by sburns** [comment]
FWIW I also see this on 3.7 using Datadog-Python37:16

**Comment by tianchu** [comment]
Just tested with the latest version of the Python layer (v17) and forwarder (v3.11.0), `env` tag gets correctly picked up. Please note, you must set "env" by tagging your Lambda function with a `env` tag (which gets applied to metrics, logs and traces), rather than using the `DD_ENV` environment variable. Also ensure the forwarder has the experimental option [DdFetchLambdaTags](https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/template.yaml#L55) on.
